os:
  - 'linux'
  - 'osx'
language: node_js
sudo: enabled
node_js:
  - 'stable'
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build --release